### ISSUE TITLE
Using mobile_net_v1 model on ios

### ISSUE THREAD

**Issue by Onotoko** [junhwanjang/face_landmark_dnn#1]
Hi,
When I am using Mobilenet_v1.mlmodel on ios I cannot detect landmarks point, please kindly let me know why?
Thanks!

**Comment by junhwanjang** [comment]
Hi,
when tested these ml models, successfully done!
I will recommend checking this sample project.
https://github.com/yinguobing/face-marks

**Comment by Onotoko** [comment]
Hi,
Wow, I used face-marks and Mobilenet_v1.mlmodel but I got none facial landmark???
 Can you send me example which using mobilenet_v1.mlmodel?
Thanks!

**Comment by junhwanjang** [comment]
Oh, Thanks! @Onotoko 
I tested Mobilenet_v1.mlmodel on github right now. I got the same error... lol
I will check and re-upload soon.

**Comment by junhwanjang** [comment]
@Onotoko  re-uploaded it :)

**Comment by Onotoko** [comment]
Thank you, I will test it :)
