### ISSUE TITLE
What Python and Keras versions?

### ISSUE THREAD

**Issue by ModarD** [junhwanjang/face_landmark_dnn#10]
Hello @junhwanjang, Thank you for the code, I'm on Python 3.5 and Keras 2.2.3 and I'm having this error when running tets_video.py

> Traceback (most recent call last):
>   File "test_video.py", line 4, in <module>
>     from mark_detector import MarkDetector
>   File "C:\Users\mwdar\Desktop\face_landmark_dnn-master\testing\mark_detector.py", line 6, in <module>from utils import smoothL1, relu6, DepthwiseConv2D, mask_weights
>   File "C:\Users\mwdar\Desktop\face_landmark_dnn-master\testing\utils.py", line 11, in <module>
>     from keras.applications.imagenet_utils import decode_predictions, _obtain_in
> put_shape
> ImportError: cannot import name '_obtain_input_shape'

I suspect it is a version problem and I tried different Keras versions with no luck.

Thank you.

**Comment by junhwanjang** [comment]
python ver 3.6.4
tensorflow==1.5.0
Keras==2.1.3

Thanks:)
