### ISSUE TITLE
The loss function of the model is not defined?

### ISSUE THREAD

**Issue by zhouhao-learning** [junhwanjang/face_landmark_dnn#11]
Hello, I am reading your code, but I see your `modeling /train_mobilenets.py` file,
` loss=smoothL1`, but smoothL1 is undefined, what is going on?

**Comment by zhouhao-learning** [comment]
Sorry, I am wrong.

**Comment by zhouhao-learning** [comment]
SmoothL1 is not defined

**Comment by junhwanjang** [comment]
sorry just pushed it:)
