### ISSUE TITLE
How to detect facial landmark?

### ISSUE THREAD

**Issue by Onotoko** [junhwanjang/face_landmark_dnn#2]
Hi junhwangjang,
Last week I run your model and looked at your code, but I don't know how do you can extract landmarks when an image push to mobilenet network. Please kindly share me some documents.
Thank you very much!

**Comment by junhwanjang** [comment]
I think it helps to look at the sample code. (https://github.com/junhwanjang/face_landmark_dnn/blob/master/testing/test_webcam.py)
The input image size is 64 x 64 with grayscale.

**Comment by Onotoko** [comment]
Hi friend,
Thank you for your help, but I not found extractly what is model handle. For example:
- Input 750x750 pixels 
- Output 136 pixels
So How model can generate output, how it knows locations of landmarks and give output?
I am not clear it, I found many document but all of them seem to how to build model to detect landmarks but not comment how we got result.
I am sorry if all of my question disturb you. Thank you :)

**Comment by junhwanjang** [comment]
Uhm not sure my answer is right ...
All models are
- Input 64 x 64 x 1 (cropped image after detect face)
- Output 136 x 1 (e.g x1, y1, ...., x68, y68)

I can say nothing but recommend looking at the code. (https://github.com/junhwanjang/face_landmark_dnn/blob/master/testing/mark_detector.py)

Thanks :)

**Comment by Onotoko** [comment]
Thanks for your kindly response, I learnt from you a lot of thing and now 
I think I should read more materials about facial landmark and deep learning (mobilenet, ...). :)
