### ISSUE TITLE
Training on custom data

### ISSUE THREAD

**Issue by Zumbalamambo** [junhwanjang/face_landmark_dnn#5]
How do I train on custom data? can you please share the script to create npy files?

**Comment by junhwanjang** [comment]
Hi, plz look up that code!
1. Create dataset using augmentation function
https://github.com/junhwanjang/face_landmark_dnn/blob/master/augmentation/test_create_dataset.py

2. Train the model using train code
https://github.com/junhwanjang/face_landmark_dnn/blob/master/modeling/train_mobilenets.py

**Comment by soans1994** [comment]
@junhwanjang 

how to use test_augment.py? i get error that no txt file. my input dataset has images and pts files.
https://github.com/junhwanjang/face_landmark_dnn/blob/master/augmentation/test_augment.py

problem with this line
pts_path = img_path.split(".")[0] + ".txt"
also tried 
pts_path = img_path.split(".")[0] + ".pts"
