### ISSUE TITLE
the speed on predicting a image or video 

### ISSUE THREAD

**Issue by JWSunny** [junhwanjang/face_landmark_dnn#6]
hi，
thanks to your sharing codes, it's very useful.

can you test the speed on predicting the images or video? such like ** fps? or ** ms per image?

Have you ported the model to android, can you provide a link to the android demo?

**Comment by junhwanjang** [comment]
Thanks @JWSunny 
I didn't ported the model to android yet.
when I checked the model on macbook, the speed is average **39fps**.

**Comment by JWSunny** [comment]
@junhwanjang thank you for your replay,
the speed 39fps is trained on basic models or mobilenets?

**Comment by junhwanjang** [comment]
@JWSunny 
The speed is
Mobilenets: 39fps
basic_models: about 42fps (but not accurate than mobilenets)

**Comment by JWSunny** [comment]
@junhwanjang OK, thanks.
how can i use the kersa_to_tf.py convert the Mobilenet_v1.hdf5 to pb file, can you provide an example including specific parameters; i find i can't use the hdf5 file in my conputer.
thank you very much, best wishes.

**Comment by JWSunny** [comment]
@junhwanjang 
hello:
when i convert hdf5 to pb, the load_model(hdf5) is error: Process finished with exit code -1073740940 (0xC0000374),  the main error is the model_config = f.attrs.get('model_config') in function load_model(); do you know why??
